# Generated by Django 4.0.1 on 2022-01-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_plans.weekday')),
            ],
        ),
    ]
